import antfu from '@antfu/eslint-config'

const ignores = [
  '.nuxt',
  '**/.nuxt/**',
  '.output',
  '**/.output/**',
  'node_modules',
  '**/node_modules/**',
  'public',
  '**/public/**',

  // Generated by `npm run db:types` from the local database. Reformatting it
  // only lasts until the next regeneration.
  'app/types/database.types.ts',

  // Vendored agent skills, pinned in skills-lock.json — upstream's code, not ours.
  '.agents',
  '**/.agents/**',

  // Owned by the Supabase CLI, which writes its own formatting.
  'supabase/config.toml',
]

export default antfu({
  // .eslintignore is no longer supported in Flat config, use ignores instead
  ignores,
  stylistic: {
    indent: 2,
    quotes: 'single',
  },
  vue: true,
  jsonc: false,
  yaml: false,
  rules: {
    'no-console': ['error', {
      allow: ['info', 'warn', 'trace', 'error', 'group', 'groupEnd'],
    }],
    'style/comma-dangle': 'off',
    'curly': ['error', 'all'],
    'node/prefer-global/process': ['error', 'always'],

    // The house style writes guard clauses on one line:
    //   if (!uid) { throw createError({ statusCode: 401, ... }) }
    // With `curly: all` forbidding the braceless form and the default limit of 1
    // forbidding the braced one, that idiom was unwritable in any form. Ignoring
    // IfStatement makes the guard count as its single inner statement, so
    // genuinely crammed lines like `a(); b()` still error.
    'style/max-statements-per-line': ['error', { max: 1, ignoredNodes: ['IfStatement'] }],
  },
}, {
  files: ['test/**/*.ts'],
  rules: {
    // Test titles name HTTP verbs and components — `POST /api/...` and
    // `AppHeader` read correctly; the autofix turns them into `pOST`/`appHeader`.
    'test/prefer-lowercase-title': 'off',
  },
})
