<script setup lang="ts">
definePageMeta({ layout: 'default' })

useHead({ title: 'Planting trees doing everyday tasks' })

// Uniform cards, so the content lives as data rather than eight near-identical
// markup blocks. Order is meaningful and matches the published page.
const services = [
  {
    name: 'Ecosia',
    href: 'https://www.ecosia.org',
    description: 'A search engine which uses the advertising revenue generated by its searches to fund reforestation projects — 250 million trees so far.',
  },
  {
    name: 'Forest',
    href: 'https://www.forestapp.cc',
    description: 'A productivity app that plants a real tree every time you stay focused and off your phone.',
  },
  {
    name: 'Flora',
    href: 'https://flora.appfluence.com',
    description: 'A productivity app that plants a real tree every time you stay focused and off your phone.',
  },
  {
    name: 'Treecard',
    href: 'https://www.treecard.org',
    description: 'A wooden debit card that funds reforestation through merchant transaction fees — and even rewards you for the steps you walk.',
  },
  {
    name: 'bunq',
    href: 'https://www.bunq.com',
    description: 'A European neobank that provides rewards in the form of trees planted.',
  },
  {
    name: 'GreenFi',
    href: 'https://www.greenfi.com',
    description: 'Rounds up card purchases to fund reforestation projects worldwide.',
  },
  {
    name: 'Treeapp',
    href: 'https://www.thetreeapp.org',
    description: 'A dedicated platform where users can plant a free tree daily simply by watching a short ad.',
  },
  {
    name: 'PlantSnap',
    href: 'https://www.plantsnap.com',
    description: 'A plant identification app that commits to planting a tree for every new user who registers.',
  },
]
</script>

<template>
  <div>
    <section class="relative py-16 px-4 overflow-hidden">
      <ImageSlot
        src="/images/everyday-tasks-hero-sunset.jpg"
        alt="Lone crooked tree silhouetted against a pink and orange sunset"
        class="absolute inset-0 w-full h-full object-cover"
      />
      <div class="absolute inset-0 bg-gray-900 opacity-45" />
      <div class="relative z-10 max-w-4xl mx-auto">
        <h1 class="text-4xl md:text-5xl font-bold text-white mb-6">
          Planting trees doing everyday tasks
        </h1>
        <p class="text-green-50 leading-relaxed max-w-3xl">
          But you can also take advantage of options offered by a vast number of technology companies to earn trees through everyday digital experiences, converting digital engagement into real-world impact with minimal lifestyle changes.
        </p>
      </div>
    </section>

    <section class="py-16 px-4 bg-white">
      <div class="max-w-5xl mx-auto">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div v-for="service in services" :key="service.name" class="border border-gray-200 rounded-2xl p-6">
            <ImageSlot alt="Organization logo placeholder" class="w-full h-32 rounded-xl object-contain bg-gray-100 mb-4" />
            <h3 class="text-xl font-semibold text-gray-900 mb-2">
              {{ service.name }}
            </h3>
            <p class="text-gray-600 leading-relaxed mb-4">
              {{ service.description }}
            </p>
            <a :href="service.href" target="_blank" rel="noopener noreferrer" class="text-green-600 font-medium text-sm hover:text-green-700">Visit website →</a>
          </div>
        </div>
      </div>
    </section>

    <section class="py-16 px-4 bg-green-600 text-center">
      <h2 class="text-2xl md:text-3xl font-bold text-white mb-6">
        Ready to track your own tree planting?
      </h2>
      <NuxtLink to="/register" class="inline-block bg-white text-green-700 px-8 py-3 rounded-full font-semibold hover:bg-green-50 transition-colors">
        Join tree troupe
      </NuxtLink>
    </section>
  </div>
</template>
