-- Splits the combined "Forest & Flora" card on the
-- "planting-trees-doing-everyday-tasks" page into two separate cards, and
-- replaces all "[Add website link]" placeholders with the real URLs
-- supplied for each of the eight products.
insert into public.pages (title, slug, content, status, show_in_nav, nav_order)
values (
  'Planting trees doing everyday tasks',
  'planting-trees-doing-everyday-tasks',
  $page$<section class="py-16 px-4 bg-gray-200">
  <div class="max-w-4xl mx-auto">
    <h1 class="text-4xl md:text-5xl font-bold text-gray-900 mb-6">Planting trees doing everyday tasks</h1>
    <p class="text-green-700 leading-relaxed max-w-3xl">But you can also take advantage of options offered by a vast number of technology companies to earn trees through everyday digital experiences, converting digital engagement into real-world impact with minimal lifestyle changes.</p>
  </div>
</section>
<section class="py-16 px-4 bg-white">
  <div class="max-w-5xl mx-auto">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
      <div class="border border-gray-200 rounded-2xl p-6">
        <div class="w-full h-32 bg-gradient-to-br from-green-100 to-emerald-50 rounded-xl flex items-center justify-center text-gray-400 text-sm mb-4">[Organization logo placeholder]</div>
        <h3 class="text-xl font-semibold text-gray-900 mb-2">Ecosia</h3>
        <p class="text-gray-600 leading-relaxed mb-4">A search engine which uses the advertising revenue generated by its searches to fund reforestation projects — 250 million trees so far.</p>
        <a href="https://www.ecosia.org" target="_blank" rel="noopener noreferrer" class="text-green-600 font-medium text-sm hover:text-green-700">Visit website →</a>
      </div>
      <div class="border border-gray-200 rounded-2xl p-6">
        <div class="w-full h-32 bg-gradient-to-br from-green-100 to-emerald-50 rounded-xl flex items-center justify-center text-gray-400 text-sm mb-4">[Organization logo placeholder]</div>
        <h3 class="text-xl font-semibold text-gray-900 mb-2">Forest</h3>
        <p class="text-gray-600 leading-relaxed mb-4">A productivity app that plants a real tree every time you stay focused and off your phone.</p>
        <a href="https://www.forestapp.cc" target="_blank" rel="noopener noreferrer" class="text-green-600 font-medium text-sm hover:text-green-700">Visit website →</a>
      </div>
      <div class="border border-gray-200 rounded-2xl p-6">
        <div class="w-full h-32 bg-gradient-to-br from-green-100 to-emerald-50 rounded-xl flex items-center justify-center text-gray-400 text-sm mb-4">[Organization logo placeholder]</div>
        <h3 class="text-xl font-semibold text-gray-900 mb-2">Flora</h3>
        <p class="text-gray-600 leading-relaxed mb-4">A productivity app that plants a real tree every time you stay focused and off your phone.</p>
        <a href="https://flora.appfluence.com" target="_blank" rel="noopener noreferrer" class="text-green-600 font-medium text-sm hover:text-green-700">Visit website →</a>
      </div>
      <div class="border border-gray-200 rounded-2xl p-6">
        <div class="w-full h-32 bg-gradient-to-br from-green-100 to-emerald-50 rounded-xl flex items-center justify-center text-gray-400 text-sm mb-4">[Organization logo placeholder]</div>
        <h3 class="text-xl font-semibold text-gray-900 mb-2">Treecard</h3>
        <p class="text-gray-600 leading-relaxed mb-4">A wooden debit card that funds reforestation through merchant transaction fees — and even rewards you for the steps you walk.</p>
        <a href="https://www.treecard.org" target="_blank" rel="noopener noreferrer" class="text-green-600 font-medium text-sm hover:text-green-700">Visit website →</a>
      </div>
      <div class="border border-gray-200 rounded-2xl p-6">
        <div class="w-full h-32 bg-gradient-to-br from-green-100 to-emerald-50 rounded-xl flex items-center justify-center text-gray-400 text-sm mb-4">[Organization logo placeholder]</div>
        <h3 class="text-xl font-semibold text-gray-900 mb-2">bunq</h3>
        <p class="text-gray-600 leading-relaxed mb-4">A European neobank that provides rewards in the form of trees planted.</p>
        <a href="https://www.bunq.com" target="_blank" rel="noopener noreferrer" class="text-green-600 font-medium text-sm hover:text-green-700">Visit website →</a>
      </div>
      <div class="border border-gray-200 rounded-2xl p-6">
        <div class="w-full h-32 bg-gradient-to-br from-green-100 to-emerald-50 rounded-xl flex items-center justify-center text-gray-400 text-sm mb-4">[Organization logo placeholder]</div>
        <h3 class="text-xl font-semibold text-gray-900 mb-2">GreenFi</h3>
        <p class="text-gray-600 leading-relaxed mb-4">Rounds up card purchases to fund reforestation projects worldwide.</p>
        <a href="https://www.greenfi.com" target="_blank" rel="noopener noreferrer" class="text-green-600 font-medium text-sm hover:text-green-700">Visit website →</a>
      </div>
      <div class="border border-gray-200 rounded-2xl p-6">
        <div class="w-full h-32 bg-gradient-to-br from-green-100 to-emerald-50 rounded-xl flex items-center justify-center text-gray-400 text-sm mb-4">[Organization logo placeholder]</div>
        <h3 class="text-xl font-semibold text-gray-900 mb-2">Treeapp</h3>
        <p class="text-gray-600 leading-relaxed mb-4">A dedicated platform where users can plant a free tree daily simply by watching a short ad.</p>
        <a href="https://www.thetreeapp.org" target="_blank" rel="noopener noreferrer" class="text-green-600 font-medium text-sm hover:text-green-700">Visit website →</a>
      </div>
      <div class="border border-gray-200 rounded-2xl p-6">
        <div class="w-full h-32 bg-gradient-to-br from-green-100 to-emerald-50 rounded-xl flex items-center justify-center text-gray-400 text-sm mb-4">[Organization logo placeholder]</div>
        <h3 class="text-xl font-semibold text-gray-900 mb-2">PlantSnap</h3>
        <p class="text-gray-600 leading-relaxed mb-4">A plant identification app that commits to planting a tree for every new user who registers.</p>
        <a href="https://www.plantsnap.com" target="_blank" rel="noopener noreferrer" class="text-green-600 font-medium text-sm hover:text-green-700">Visit website →</a>
      </div>
    </div>
  </div>
</section>
<section class="py-16 px-4 bg-green-600 text-center">
  <h2 class="text-2xl md:text-3xl font-bold text-white mb-6">Ready to track your own tree planting?</h2>
  <a href="/register" class="inline-block bg-white text-green-700 px-8 py-3 rounded-full font-semibold hover:bg-green-50 transition-colors">Join tree troupe</a>
</section>$page$,
  'published',
  false,
  0
)
on conflict (slug) do update
  set content = excluded.content,
      updated_at = now();
